# Generated by Django 6.0.3 on 2026-03-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Excused', 'Excused')], max_length=10),
        ),
    ]
